# Generated by Django 5.2 on 2025-07-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(max_length=20),
        ),
    ]
