# Generated by Django 5.2 on 2025-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0002_accesslog_ip_address_alter_accesslog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
