# Generated by Django 5.2 on 2025-07-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0003_accesslog_city_accesslog_country_accesslog_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
